steps:
  # Install Node.js dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['ci']

  # Build web assets
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Sync Capacitor with Android
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['cap', 'sync', 'android']

  # Build Android APK
  - name: 'gcr.io/cloud-builders/android'
    args: ['./gradlew', 'assembleRelease']
    dir: 'android'

  # Build Android App Bundle
  - name: 'gcr.io/cloud-builders/android'
    args: ['./gradlew', 'bundleRelease']
    dir: 'android'

artifacts:
  objects:
    location: 'gs://besmi-android-builds'
    paths:
      - 'android/app/build/outputs/apk/release/app-release.apk'
      - 'android/app/build/outputs/bundle/release/app-release.aab'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'